name: Short Regression Tests

on:
  pull_request:

jobs:
  platform:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    # Clone this repo
    - name: Checkout
      uses: actions/checkout@v3

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: AI Code Reviewer
      uses: your-username/ai-code-reviewer@2.7.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
        exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas